[package]
name = "sealpir"
version = "0.1.0"
authors = ["Sebastian Angel <sebs@cs.utexas.edu>"]
edition = "2018"

[build-dependencies]
cc = "1.0"
cmake = "0.1"

[dependencies]
libc = "0.2"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
